---
title: "Portfolio Project Proposal"
author: "Kathryn Denning"
date: "2/4/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup and data import, echo = FALSE, warning = FALSE, message=FALSE, error=FALSE}
library(rio)
library(here)
library(tidyverse)
library(magrittr)
library(RColorBrewer)
library(ggridges)
library(XML)
knitr::opts_chunk$set()

x <- readHTMLTable("http://www.nuforc.org/webreports/ndxe201901.html")
ufo_jan19 <- plyr::ldply(x, data.frame)

y <- readHTMLTable("http://www.nuforc.org/webreports/ndxlOR.html")
ufo_oregon <- plyr::ldply(y, data.frame)
```

#Description of data:
These two datafiles come from the National UFO Reporting Center (http://www.nuforc.org/index.html). One dataset includes all of the reported UFO sightings for January 2019. The other file contains all of the reported UFO sightings in Oregon on record. Both datasets include the following variables: date/time, city, state (though for the Oregon dataset this is all one state), shape (of the reported UFO), duration (of the object's appearance), summary (description by the reporter), and date posted (when it was posted on the website). A .id column appeared when converting both datafiles into a dataframe, but is not on the website and all datafilesand will be deleted.

#Description of plots

All plots will be made for a general public audience, though the scientific(?) community interested in UFO sightings might also be interested.

###Plot 1: Choropleth of frequency of reports across US by location
Plot showing the shape of the country with colors changing on the map according to the density of the reports, using changes in color like a heatmap and ideally the viridis color palette. I plan on doing this at the city level within each state, but hopefully can still have the outline of each state visible in the map of the US as well.

###Plot 2: A heatmap showing the frequency of reports over days in the last month
Heatmap will show frequency of reports on the y-axis and time on the x-axis. I plan on using the viridis color palette.

###Plot 3: A scatterplot showing reports over days in the last month by shape
Scatterplot showing the frequency of reports on the y-axis across time in days on x-axis grouped by shape. I plan on displaying shape by (ideally) using corresponding shapes as the dots, though otherwise I might identify shape by color or with lines/geom_ribbon corresponding with shape. 

###Plot 4: Choropleth of frequency of reports across Oregon by location
Plot showing the shape of the state of Oregon with colors changing on the map according to the density of the reports, using changes in color like a heatmap and ideally the viridis color palette. I would like to have either county outlines on the state and cities also identified on the map for reference (like Eugene, Portland, Bend, McMinville (UFO festival location, has to be identified!)).

###Plot 5: A heatmap showing frequency of reports in Oregon over time
Heatmap will show frequency of reports on the y-axis and time on the x-axis. I plan on using the viridis color palette.

###Plot 6: A plot showing frequency of reports by city in Oregon (top 10)
Barplot with frequency on the y-axis and city on the x-axis, most likely with the axes switched. I haven't thought of what color scheme I might want to designate city.




